import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  SCENARIOS,
  isScenarioId,
  scenarioById,
  scenarioSummary,
  type ScenarioId,
  type ScenarioManifestEntry,
} from './scenarios'

/**
 * TT-4, "Import a scenario". Written from the acceptance criteria (KB-3's scenario table and
 * TT-4's own notes on where scenario data lives) and from .claude/plans/TT-4.md sections 3 and
 * 5. Does not open scenarios.ts.
 *
 * C20, the drift guard, reads the real files under public/scenarios/ with node:fs rather than
 * asserting against numbers copied into this file, so the manifest cannot silently drift from
 * the shipped data (KB-3: "generated by a seeded script so regenerating produces identical
 * output").
 */

const DIR = dirname(fileURLToPath(import.meta.url))

type ScenarioFileMeta = {
  scenario: string
  guests: number
  tables: { roundTables: number; seatsEach: number; topTableSeats: number }
  seats: number
  spare: number
}

type ScenarioFile = {
  meta: ScenarioFileMeta
  guests: unknown[]
}

function readScenarioFile(id: ScenarioId): ScenarioFile {
  const path = join(DIR, '../../public/scenarios', `${id}.json`)
  return JSON.parse(readFileSync(path, 'utf8')) as ScenarioFile
}

function entryFor(id: ScenarioId): ScenarioManifestEntry {
  const entry = SCENARIOS.find((candidate: ScenarioManifestEntry) => candidate.id === id)
  if (!entry) throw new Error(`${id} is missing from SCENARIOS`)
  return entry
}

describe('SCENARIOS (C19)', () => {
  it('lists the three scenarios in KB-3 order, with KB-3 names, guest counts and rooms', () => {
    expect(SCENARIOS).toEqual([
      {
        id: 'small-and-cosy',
        name: 'Small and cosy',
        guestCount: 40,
        room: { roundTables: 4, seatsEach: 8, topTableSeats: 8 },
      },
      {
        id: 'adding-up',
        name: 'Adding up',
        guestCount: 70,
        room: { roundTables: 9, seatsEach: 8, topTableSeats: 6 },
      },
      {
        id: 'celebrity-scale',
        name: 'Celebrity scale',
        guestCount: 200,
        room: { roundTables: 26, seatsEach: 8, topTableSeats: 8 },
      },
    ])
  })
})

describe('scenarioSummary (C2, C14)', () => {
  it('works out 40 seats and 0 spare for Small and cosy', () => {
    expect(scenarioSummary(entryFor('small-and-cosy'))).toMatchObject({ totalSeats: 40, spare: 0 })
  })

  it('works out 78 seats and 8 spare for Adding up', () => {
    expect(scenarioSummary(entryFor('adding-up'))).toMatchObject({ totalSeats: 78, spare: 8 })
  })

  it('works out 216 seats and 16 spare for Celebrity scale', () => {
    expect(scenarioSummary(entryFor('celebrity-scale'))).toMatchObject({ totalSeats: 216, spare: 16 })
  })
})

describe('the manifest cannot drift from the shipped files (C20)', () => {
  it('small-and-cosy: manifest matches public/scenarios/small-and-cosy.json exactly', () => {
    const entry = entryFor('small-and-cosy')
    const file = readScenarioFile('small-and-cosy')
    const summary = scenarioSummary(entry)

    expect(file.meta.scenario).toBe(entry.name)
    expect(file.meta.guests).toBe(entry.guestCount)
    expect(file.meta.tables).toEqual(entry.room)
    expect(file.meta.seats).toBe(summary.totalSeats)
    expect(file.meta.spare).toBe(summary.spare)
    expect(file.guests.length).toBe(entry.guestCount)
  })

  it('adding-up: manifest matches public/scenarios/adding-up.json exactly', () => {
    const entry = entryFor('adding-up')
    const file = readScenarioFile('adding-up')
    const summary = scenarioSummary(entry)

    expect(file.meta.scenario).toBe(entry.name)
    expect(file.meta.guests).toBe(entry.guestCount)
    expect(file.meta.tables).toEqual(entry.room)
    expect(file.meta.seats).toBe(summary.totalSeats)
    expect(file.meta.spare).toBe(summary.spare)
    expect(file.guests.length).toBe(entry.guestCount)
  })

  it('celebrity-scale: manifest matches public/scenarios/celebrity-scale.json exactly', () => {
    const entry = entryFor('celebrity-scale')
    const file = readScenarioFile('celebrity-scale')
    const summary = scenarioSummary(entry)

    expect(file.meta.scenario).toBe(entry.name)
    expect(file.meta.guests).toBe(entry.guestCount)
    expect(file.meta.tables).toEqual(entry.room)
    expect(file.meta.seats).toBe(summary.totalSeats)
    expect(file.meta.spare).toBe(summary.spare)
    expect(file.guests.length).toBe(entry.guestCount)
  })
})

describe('isScenarioId', () => {
  it('accepts the three known slugs', () => {
    expect(isScenarioId('small-and-cosy')).toBe(true)
    expect(isScenarioId('adding-up')).toBe(true)
    expect(isScenarioId('celebrity-scale')).toBe(true)
  })

  it('rejects "custom", the empty string, null and an unknown slug', () => {
    expect(isScenarioId('custom')).toBe(false)
    expect(isScenarioId('')).toBe(false)
    expect(isScenarioId(null)).toBe(false)
    expect(isScenarioId('not-a-scenario')).toBe(false)
  })
})

describe('scenarioById', () => {
  it('returns the matching entry for each known id', () => {
    for (const entry of SCENARIOS) {
      expect(scenarioById(entry.id)).toEqual(entry)
    }
  })

  it('throws on an unknown id', () => {
    expect(() => scenarioById('not-a-scenario' as ScenarioId)).toThrow()
  })
})
